id: P1447B067
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: bo
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    0b14a9048270438799413b7c3ad64d2c:
      title: Brief Dharmapālas Offering
      parent: General
    be9783c6fffd43469a5ebc4b17e65230:
      title: Brief Protectors Practice
      parent: General
    be3965a9b628434cb0ae58352fba0e6b:
      title: Expeditious Activity Torma Offering
      parent: General
    a1e5842b292d4391ba098b1689796260:
      title: Wayfaring Offering
      parent: General
    66b21c2e29b945c5826dd4fe87f306ec:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    9fe5261bba4c4eaa8d1a4e8058464a78:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    d8ccec701ae34c99829c622120d493c1:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    f30d6b3e3b7843bdb606e497e054c4fc:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    c7bfd4e9369746a49a357fb4d2846b20:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    c1796ff0ab074088bb0feecf2a87abec:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    f6f98dd1c22d4978bb8d4d3e8fa08c86:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    9bab2bf1e62548e996b61f968e98504d:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    b06fabe3cf114e049fb1cdcf3f656f7d:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    c353cb658d164772b31f4f3f1f3d6664:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    0fd5c565864a4e7eb7780d592fd7efb7:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    bf66f719a48e4c60af9122b20ec363a8:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    36a4c2f03e0d4364b643cf2e5d59be04:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    c184a98d067d47afab40d7db18fa93ec:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    264989eee7cf445290ab00cd2c719642:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    e17a76656419414ab0394ef81d1f98a2:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    3a4bb660ea9a46a0a3c78172b27a407e:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    61df527a873c4e09b0efd5332acc7cc7:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    8b72cdce552844758d8125b1199c132f:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    3d810a24054049cd8163d84b1e807cf3:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    bd0ae3144c0745adb9d07994d55e0c79:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    fdf9baf388034df99b6146c20c8276c3:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.286067'
last_modified_at: '2022-03-01T03:27:20.286069'
statistics:
  total_words: 10585
  total_non_words: 1573
quality:
  non_words_ratio: 0.15
